---
# Requires environment variables for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['KITCHEN_AWS_SSH_KEY_ID'] %>
  region: <%= ENV['KITCHEN_AWS_REGION'] %>
  availability_zone: <%= ENV['KITCHEN_AWS_REGION_ZONE'] %>
  subnet_id: <%= ENV['KITCHEN_AWS_SUBNET_ID'] %>
  instance_type: <%= ENV['KITCHEN_EC2_INSTANCE_TYPE'] %>
  associate_public_ip: <%= ENV['KITCHEN_EC2_PUBLIC_IP'] %>
  security_group_ids: <%= ENV['KITCHEN_EC2_SECURITY_GROUP_IDS'] %>
  interface: <%= ENV['KITCHEN_EC2_INTERFACE'] %>
  retryable_tries: 120

transport:
  ssh_key: <%= ENV['KITCHEN_AWS_KEY_FILE'] %>
  connection_timeout: 10
  connection_retries: 5

provisioner:
  product_name: chef
  product_version: <%= ENV['CHEF_OMNIBUS_VERSION'] %>

platforms:
  - name: rhel-7.3-<%= ENV['CHEF_OMNIBUS_VERSION'] %>
    driver:
      image_id: <%= ENV['RHEL_73_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['RHEL_73_USER'] %>
  - name: rhel-6-<%= ENV['CHEF_OMNIBUS_VERSION'] %>
    driver:
      image_id: <%= ENV['RHEL_6_AMI_ID'] %>
      user_data: <%= ENV['KITCHEN_EC2_USER_DATA'] %>
    transport:
      username: <%= ENV['RHEL_6_USER'] %>
suites:
  - name: default
    run_list:
      - recipe[cloudpassage::default]
    attributes:
      cloudpassage:
        agent_key: <%= ENV['HALO_AGENT_KEY'] %>
        linux_agent_version: <%= ENV['HALO_AGENT_VERSION'] %>
