rvm:
  - 2.4.0
env:
  - CHEF_DK_VERSION=3.0.4

sudo: required

before_install: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk -v $CHEF_DK_VERSION
install:
  - chef exec bundle install
# script:
#   - chef exec berks install
#   - chef exec rake travis
#   - chef exec rake integration:windows
#   - chef exec rake integration:ubuntu
#   - chef exec rake integration:rhel
#   - chef exec rake integration:amzn
#   - chef exec rake integration:centos
#   - chef exec rake integration:debian
#   - chef exec rake integration:oracle
